name: Build Book

on: push

jobs:
  build_book:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: >- # mulitline arguments
            -f gfm
            --toc
            --lua-filter plugins/pagebreak.lua

            -V linkcolor:blue 
            -V geometry:a4paper 
            -V geometry:margin=2cm 
            --pdf-engine=xelatex 
            --output=output/book.pdf 
            ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
# -H plugins/inline_code.tex
# -H plugins/cover.tex
# -H plugins/quote.tex
